### ISSUE TITLE
Flag generation issue

### ISSUE THREAD

**Issue by Cr0w-Aragorn** [Luxus-Oderus-Humongous/CTF_Prototype#1]
Hey Pubert,

I think there is an issue with flag code leading to an incorrect output, could you take a look at it.
I also think a more intuitive front-end could be added to help the new recruits in using the tool, might whip one up later and request it.

**Comment by Luxus-Oderus-Humongous** [comment]
Hey,

Thanks for reaching out about this Aragorn, the flag used during testing wasn't for final release. If you want to test the code base offline the correct flag is:
\x5d\x59\x25\x0c\x04\x16\x4f\x16\x08\x66\x51\x1b\x6e\x0d\x31\x41\x1b\x2b\x64\x52\x1e\x53\x68\x42\x18\x20

Regarding the front-end I will make sure to pull through the additions you make to a splash screen as it would be useful to feature one for the new recruits
